// import en from '../../languageConfig/local/en';

const initialState = {
  populateNewCustomerListState: false,
  setProductForReveiveItem: null,
  setProductsBarcode: [],
  products: [],
  selectedProduct: {},
  selectedCategory: {},
  promotion: null,
  topProducts: [],
  cart: {},
  emptyCartFlag: false,
  paymentJournals: [],
  customers: [],
  contactList: [],
  orders: [],
  orderDetails: {},
  moneyIn: {},
  moneyOut: {},
  sessions: [],
  pos_session_id: null,
  sessionSummary: {},
  reasons: [],
  creditHistory: [],
  searchedProducts: [],
  searchedOrders: [],
  searchedCustomers: [],
  user: null,
  // user_onboard:{},
  setCustomerForOrder: null,
  setCustomerForDetails: null,
  setCustomerForUdhaar: null,
  setCustomerForViewProfileOrEdit: null,
  currentOrderInfo: {},
  // username: null,
  // language: {...en},
  analyticsHome: {
    storeViews: null,
    storeRevenue: null,
    storeOrders: null,
    start_date: null,
    end_date: null,
  },
  analytics: {
    total_revenue: 0,
    total_cogs: 0,
    gross_margin_value: 0,
    gross_margin_percentage: 0,
    customers_served: 0,
    sales_by_day: {},
    sales_by_hour: {},
    avg_items_purchased: 0,
    avg_order_value: 0,
    payment_methods: {},
    top_items_by_sales: [],
    lowest_items_by_sales: [],
  },
  paymentMethod: '',
  globalDiscount: 0,
  categories: {
    mainCategories: [],
    subCategories: [],
    products: [],
    getProductFlag: false,
  },
  dukaanCategories: {
    mainCategories: [],
    products: [],
  },
  userOnboard: false,
  summary: {
    udhaar: 0,
    advance: 0,
    netBalance: 0,
  },
  loading: false,
  backupLoading: false,
  payment_progress: 0,
  payment_total: 0,
  deleted_progress: 0,
  deleted_total: 0,
  customer_progress: 0,
  customer_total: 0,
  outstanding_progress: 0,
  outstanding_total: 0,
  user_progress: 0,
  restoring: false,
  customers_to_restore: [],
  quiz_start_date: null,
  quiz_end_date: null,
};

export default initialState;
