export const BRAND = {
  GET_BRANDS: 'GET_BRANDS',
};
export const PAYMENT = {
  SET_PAYMENT_METHOD: 'SET_PAYMENT_METHOD',
};
export const CATEGORY = {
  GET_CATEGORIES: 'GET_CATEGORIES',
  GET_SUB_CATEGORY: 'GET_SUB_CATEGORY',
  GET_CATEGORY_FOR_EDIT: 'GET_CATEGORY_FOR_EDIT',
  GET_CATEGORIZED_PRODUCT: 'GET_CATEGORIZED_PRODUCT',
  RESET_GET_CATEGORIZED_PRODUCT: 'RESET_GET_CATEGORIZED_PRODUCT',
  ADD_CATEGORY: 'ADD_CATEGORY',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  REMOVE_CATEGORY: 'REMOVE_CATEGORY',
  ADD_MULTIPLE_CATEGORIES: 'ADD_MULTIPLE_CATEGORIES',
};

export const COMPANY = {
  GET_COMPANIES: 'GET_COMPANIES',
};
export const ANALYTICS_MERCHANT = {
  GET_ANALYTICS_COUNTER: 'GET_ANALYTICS_COUNTER',
};
export const NEW_ARRIVAL = {
  GET_NEW_ARRIVALS: 'GET_NEW_ARRIVALS',
};
export const CONTACT = {
  GET_CONTACT_LIST: 'GET_CONTACT_LIST',
};

export const PRODUCT = {
  SET_PRODUCTS_BARCODE: 'SET_PRODUCTS_BARCODE',
  GET_TOP_PRODUCTS: 'GET_TOP_PRODUCTS',
  SET_PRODUCT_FOR_RECEIVE_ITEM: 'SET_PRODUCT_FOR_RECEIVE_ITEM',
  RESET_PRODUCT_FOR_RECEIVE_ITEM: 'RESET_PRODUCT_FOR_RECEIVE_ITEM',
  CLEAR_SEARCHED_PRODUCTS: 'CLEAR_SEARCHED_PRODUCTS',
  SEARCHED_PRODUCT: 'SEARCHED_PRODUCT',
  SEARCHED_PRODUCT_FAIL: 'SEARCHED_PRODUCT_FAIL',
  GET_PRODUCTS: 'GET_PRODUCTS',
  ADD_PRODUCT: 'ADD_PRODUCT',
  ADD_PRODUCTS: 'ADD_PRODUCTS',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  UPDATE_PRODUCT_ID: 'UPDATE_PRODUCT_ID',
  UPDATE_PRODUCT_STATUS: 'UPDATE_PRODUCT_STATUS',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT',
  GET_PRODUCT_FOR_EDIT: 'GET_PRODUCT_FOR_EDIT',
  UPDATE_DELETED_BY_CATEGORIES: 'UPDATE_DELETED_BY_CATEGORIES',
  RESET_PRODUCTS: 'RESET_PRODUCTS',
};

export const DISCOUNT = {
  SET_GLOBAL_DISCOUNT: 'SET_GLOBAL_DISCOUNT',
  RESET_GLOBAL_DISCOUNT: 'RESET_GLOBAL_DISCOUNT',
};

// export const LANGUAGE = {
//   SET_LANGUAGE: 'SET_LANGUAGE',

//   SET_URDU_LANGUAGE: 'SET_URDU_LANGUAGE',
//   SET_SINDHI_LANGUAGE: 'SET_SINDHI_LANGUAGE',
//   SET_EN_LANGUAGE: 'SET_EN_LANGUAGE',
// };

export const CUSTOMER = {
  SET_FLAG_FOR_POPULATENEWCUSTOMERSCREEN_STATE:
    'SET_FLAG_FOR_POPULATENEWCUSTOMERSCREEN_STATE',

  RESET_FLAG_FOR_POPULATENEWCUSTOMERSCREEN_STATE:
    'RESET_FLAG_FOR_POPULATENEWCUSTOMERSCREEN_STATE',

  SET_CUSTOMER_FOR_VIEWPROFILE_OR_EDIT: 'SET_CUSTOMER_FOR_VIEWPROFILE_OR_EDIT',
  RESET_CUSTOMER_FOR_VIEWPROFILE_OR_EDIT:
    'RESET_CUSTOMER_FOR_VIEWPROFILE_OR_EDIT',
  UPDATE_CUSTOMER_ID: 'UPDATE_CUSTOMER_ID',

  SET_CUSTOMER_FOR_UDHAAR: 'SET_CUSTOMER_FOR_UDHAAR',
  RESET_CUSTOMER_FOR_UDHAAR: 'RESET_CUSTOMER_FOR_UDHAAR',

  CLEAR_SEARCHED_CUSTOMER: 'CLEAR_SEARCHED_CUSTOMER',

  SET_CUSTOMER_FOR_DETAILS: 'SET_CUSTOMER_FOR_DETAILS',
  RESET_CUSTOMER_FOR_DETAILS: 'RESET_CUSTOMER_FOR_DETAILS',
  SET_CUSTOMER_FOR_ORDER: 'SET_CUSTOMER_FOR_ORDER',
  RESET_CUSTOMER_FOR_ORDER: 'RESET_CUSTOMER_FOR_ORDER',
  DELETE_CUTOMER: 'DELETE_CUTOMER',
  SEARCHED_CUSTOMER: 'SEARCHED_CUSTOMER',
  GET_CUSOTMERS: 'GET_CUSOTMERS',
  ADD_CUSTOMER: 'ADD_CUSTOMER',
  UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
  UPDATE_CUSTOMER_OUTSTANDING_BALANCE: 'UPDATE_CUSTOMER_OUTSTANDING_BALANCE',
  DELETE_CUTOMER_FROM_REALM: 'DELETE_CUTOMER_FROM_REALM',
  ADD_CUSTOMER_FOR_RESTORE_PAYMENT: 'ADD_CUSTOMER_FOR_RESTORE_PAYMENT',
  REMOVE_CUSTOMER_FOR_RESTORE_PAYMENT: 'REMOVE_CUSTOMER_FOR_RESTORE_PAYMENT',
  RESET_CUSTOMER_STATE: 'RESET_CUSTOMER_STATE',
};

export const CREDIT_HISTORY = {
  GET_CREDIT_HISTORY: 'GET_CREDIT_HISTORY',
  CLEAR_CREDIT_HISTORY: 'CLEAR_CREDIT_HISTORY',
  ADD_TO_CREDIT_HISTORY: 'ADD_TO_CREDIT_HISTORY',
  DELETE_TRANSACTION: 'DELETE_TRANSACTION',
  UPDATE_TRANSACTION: 'UPDATE_TRANSACTION',
};

export const PAYMENT_JOURNAL = {
  GET_ALL_JOURNALS: 'GET_ALL_JOURNALS',
};

export const PROMOTION = {
  GET_PROMOTIONS: 'GET_PROMOTIONS',
};

export const CART = {
  SET_EMPTY_CART_FLAG: 'SET_EMPTY_CART_FLAG',
  CLEAR_EMPTY_CART_FLAG: 'CLEAR_EMPTY_CART_FLAG',
  UPDATE_PRODUCT_TO_CART: 'UPDATE_PRODUCT_TO_CART',
  ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
  CLEAR_DISCOUNT: 'CLEAR_DISCOUNT',
  REMOVE_PRODUCT_FROM_CART: 'REMOVE_PRODUCT_FROM_CART',
  INC_PRODUCT_COUNT: 'INC_PRODUCT_COUNT',
  DEC_PRODUCT_COUNT: 'DEC_PRODUCT_COUNT',
  POPULATE_CART: 'POPULATE_CART',
  EMPTY_CART: 'EMPTY_CART',
  ADD_DISCOUNT: 'ADD_DISCOUNT',
  ADD_CUSTOM_PRODUCT: 'ADD_CUSTOM_PRODUCT',
  ADD_DISCOUNT_PRODUCT: 'ADD_DISCOUNT_PRODUCT',
  UPDATE_PRODUCT_COUNT: 'UPDATE_PRODUCT_COUNT',
};

export const ORDER = {
  SEARCHED_ORDER: 'SEARCHED_ORDER',
  SAVE_CURRENT_ORDER_INFO: 'SAVE_CURRENT_ORDER_INFO',
  CLEAR_CURRENT_ORDER_INFO: 'CLEAR_CURRENT_ORDER_INFO',
  SAVE_ORDER: 'SAVE_ORDER',
  GET_ORDERS: 'GET_ORDERS',
  DELETE_ORDER: 'DELETE_ORDER',
  UPDATE_STATUS: 'UPDATE_STATUS',
  SET_DELIVERY_DATE: 'SET_DELIVERY_DATE',
};

export const ORDER_DETAIL = {
  GET_ORDER: 'GET_ORDER',
};

export const MONEYIN = {
  PUT_MONEY_IN: 'PUT_MONEY_IN',
};

export const MONEYOUT = {
  TAKE_MONEY_OUT: 'TAKE_MONEY_OUT',
};

export const SESSION = {
  GET_SESSIONS: 'GET_SESSIONS',
  GET_SESSION_SUMMARY: 'GET_SESSION_SUMMARY',
  SET_POS_SESSION_ID: 'SET_POS_SESSION_ID',
  RESET_POS_SESSION_ID: 'RESET_POS_SESSION_ID',
};
export const REASONS = {
  GET_REASONS: 'GET_REASONS',
};
export const DB = {
  OPEN_DB: 'OPEN_DB',
};

export const USER = {
  UPDATE_USER: 'UPDATE_USER',
  SET_USERNAME: 'SET_USERNAME',
  REMOVE_USERNAME: 'REMOVE_USERNAME',
  GET_USER: 'GET_USER',
  UPDATE_USER: 'UPDATE_USER',
};
export const TOUR = {
  ENABLE_TOUR: 'ENABLE_TOUR',
  DISABLE_TOUR: 'DISABLE_TOUR',
};

export const ANALYTICS = {
  TOTAL_REVENUE: 'TOTAL_REVENUE',
  TOTAL_COGS: 'TOTAL_COGS',
  GROSS_MARGIN_VALUE: 'GROSS_MARGIN_VALUE',
  GROSS_MARGIN_PERCENTAGE: 'GROSS_MARGIN_PERCENTAGE',
  CUSTOMERS_SERVED: 'CUSTOMERS_SERVED',
  SALES_BY_DAY: 'SALES_BY_DAY',
  SALES_BY_HOUR: 'SALES_BY_HOUR',
  AVG_ITEMS_PURCHASED: 'AVG_ITEMS_PURCHASED',
  AVG_ORDER_VALUE: 'AVG_ORDER_VALUE',
  PAYMENT_METHODS: 'PAYMENT_METHODS',
  TOP_ITEMS_BY_SALES: 'TOP_ITEMS_BY_SALES',
  LOWEST_ITEMS_BY_SALES: 'LOWEST_ITEMS_BY_SALES',
};

export const BUSINESS_CARD = {
  ADD_BUSINESS_CARD: 'ADD_BUSINESS_CARD',
  GET_BUSINESS_CARD: 'GET_BUSINESS_CARD',
  UPDATE_BUSINESS_CARD: 'UPDATE_BUSINESS_CARD',
};

export const SUMMARY = {
  SET_SUMMARY: 'SET_SUMMARY',
};

export const LOADING = {
  SET_LOADING_TRUE: 'SET_LOADING_TRUE',
  SET_LOADING_FALSE: 'SET_LOADING_FALSE',
  SET_BACKUP_LOADING_TRUE: 'SET_BACKUP_LOADING_TRUE',
  SET_BACKUP_LOADING_FALSE: 'SET_BACKUP_LOADING_FALSE',
  SET_RESTORING_TRUE: 'SET_RESTORING_TRUE',
  SET_RESTORING_FALSE: 'SET_RESTORING_FALSE',
};

export const PROGRESS = {
  SET_DELETED_PROGRESS: 'SET_DELETED_PROGRESS',
  SET_PAYMENT_PROGRESS: 'SET_PAYMENT_PROGRESS',
  SET_CUSTOMER_PROGRESS: 'SET_CUSTOMER_PROGRESS',
  SET_USER_PROGRESS: 'SET_USER_PROGRESS',
  SET_TOTAL_PAYMENT: 'SET_TOTAL_PAYMENT',
  SET_TOTAL_CUSTOMER: 'SET_TOTAL_CUSTOMER',
  SET_TOTAL_DELETED: 'SET_TOTAL_DELETED',
  SET_OUTSTANDING_PROGRESS: 'SET_OUTSTANDING_PROGRESS',
  SET_TOTAL_OUTSTANDING: 'SET_TOTAL_OUTSTANDING',
};

export const QUIZ = {
  SET_QUIZ_START_DATE: 'SET_QUIZ_START_DATE',
  SET_QUIZ_END_DATE: 'SET_QUIZ_END_DATE',
};
